apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome</title>
        <!-- Include Bootstrap CSS from CDN -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      </head>
      <body>
        <div class="container">
          <div class="jumbotron mt-5">
            <h1 class="display-4">Welcome, DevOps Engineer!</h1>
<<<<<<< HEAD
           <p class="lead">I Finally get the webhook to work with the ngrok tool that helps with public IP to communicate the ArgoCD Server (localhost) with the GIT server </p>
            <p class="lead">Hi DevOps Engineer Chika will bealways here, I got Synced using ArgoCD.</p>
=======
            <p class="lead">Still trying with the ngrok tunnel to link host with git repo, I got Synced using ArgoCD.</p>
            <p class="lead">Hi DevOps Engineer Chika will be always here, I got Synced using ArgoCD.</p>
>>>>>>> 1041661f1c6aba436cdb60a031f4e15e8ad9fe3a
          </div>
        </div>
      </body>
    </html>
